// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq_uAAp6KZGVUFM8R6qCAau50_-f29XrU',
    appId: '1:578038726673:web:f22996109666b693b371b0',
    messagingSenderId: '578038726673',
    projectId: 'commuter-5d00c',
    authDomain: 'commuter-5d00c.firebaseapp.com',
    storageBucket: 'commuter-5d00c.appspot.com',
    measurementId: 'G-N27KQFXGMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIqEm5rHB4fw_-jcduZlnmrZ4eUbE5Dlg',
    appId: '1:578038726673:android:e4e5f75bdb58972bb371b0',
    messagingSenderId: '578038726673',
    projectId: 'commuter-5d00c',
    storageBucket: 'commuter-5d00c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiX1FlWsMRwZNUqmeoswQvRKzNYs-20GA',
    appId: '1:578038726673:ios:68b162c6c85d9e55b371b0',
    messagingSenderId: '578038726673',
    projectId: 'commuter-5d00c',
    storageBucket: 'commuter-5d00c.appspot.com',
    iosClientId: '578038726673-81hco3v7iuk05to2ceav1qg1fdqn4e41.apps.googleusercontent.com',
    iosBundleId: 'com.example.logo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiX1FlWsMRwZNUqmeoswQvRKzNYs-20GA',
    appId: '1:578038726673:ios:68b162c6c85d9e55b371b0',
    messagingSenderId: '578038726673',
    projectId: 'commuter-5d00c',
    storageBucket: 'commuter-5d00c.appspot.com',
    iosClientId: '578038726673-81hco3v7iuk05to2ceav1qg1fdqn4e41.apps.googleusercontent.com',
    iosBundleId: 'com.example.logo',
  );
}
